import {createSlice} from '@reduxjs/toolkit'

export const counterSlice = createSlice({
    name: "counter",
    initialState:{
        value:0,
    },
    reducers:{
        increment: (state) => {
            state.value=state.value+1
        },
        decrement: (state) => {
            state.value=state.value-1
        }
    }
})

// Export the actions generated by createSlice
export const { increment, decrement } = counterSlice.actions;

// Export the reducer
export default counterSlice.reducer;